#ifndef LOGGERDB_STATUS_H
#define LOGGERDB_STATUS_H

#define LOGGERDB_OK 0
#define LOGGERDB_ERROR 1

#define LOGGERDB_NOTADB 2
#define LOGGERDB_NOTFOUND 3
#define LOGGERDB_INVALID 4
#define LOGGERDB_IOERROR 5

#define LOGGERDB_BUSY 6

#define LOGGERDB_NOMEM 7
#define LOGGERDB_FDERR 8
#define LOGGERDB_FDBAD 9

#endif
